# Enable mouse emulation.
# CONFIG_ZMK_POINTING=y

# Change idle settings
# CONFIG_ZMK_IDLE_TIMEOUT=30000

# Deep sleep settings
# CONFIG_ZMK_SLEEP=y
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Custom keyboard name (max. 16 characters)
CONFIG_ZMK_KEYBOARD_NAME="LorsKeyb"

CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# Aktiviert das Dongle-Modul für beide Akkus auf einem Display
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y

# Batteriedaten der blinden rechten Hälfte abrufen
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
