# Enable mouse emulation.
# CONFIG_ZMK_POINTING=y

# Change idle settings
# CONFIG_ZMK_IDLE_TIMEOUT=30000

# Deep sleep settings
# CONFIG_ZMK_SLEEP=y
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Custom keyboard name (max. 16 characters)
CONFIG_ZMK_KEYBOARD_NAME="LorsKeyb"

CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# Aktiviert das e-Paper Layout des mctechnology17 Moduls
CONFIG_NICE_EPAPER_ON=y

# Erlaubt das Auslesen des rechten Akkus
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
